### ISSUE TITLE
Theme no render in frontpage

### ISSUE THREAD

**Issue by rica-carv** [rica-carv/e107_theme-selospt_v2#1]
Theme no render in frontpage
On subpages it renders, on frontpage, it's a simple page without menus, menu links, etc....

**Comment by Jimmi08** [comment]
Did you add FRONTPAGE to homepage layout in your theme manager? If yes, what is set as Front Page (news, welcome message...) and what layout did you for homepage?

**Comment by rica-carv** [comment]
Grrrrrr. Now it appears.... Damn cache....
I've restarted my localhost development server, and it appears now as i'm intended.....
Grrrrrrrrrrrrrrrrr.........

**Comment by rica-carv** [comment]
Well, sung victory too soon....
"Bug" is back again, and the issue is indeed when rendering FRONTPAGE (ie, going to site index)...

I can't change anything on theme manager...

**Comment by Jimmi08** [comment]
Just installed, theme manager working correct
![image](https://cloud.githubusercontent.com/assets/5429548/13932979/201a6dee-efab-11e5-9803-cadd7dcee344.png)

But this is result:
![image](https://cloud.githubusercontent.com/assets/5429548/13933016/5ae776d8-efab-11e5-8c0f-881f717138b7.png)

**Comment by rica-carv** [comment]
@Jimmi08 : That's the old one, the one here now in github doesn't have Jumbotron, and there's where i have all these issues....

**Comment by Jimmi08** [comment]
@rica-carv I was sure I downloaded latest version. But from the look at your plugin.xml here- I did it the same way at first and got the same error. Just don't use only one layout and don't use name default for it  (something of that helped)  Funny, I started exactly the same way as you before.

**Comment by rica-carv** [comment]
@Jimmi08 Well, seems i got it working... Just renamed the layout[´default´] to layout['main'], and it apparently seems to work...
Many thanks for all the help....
