### ISSUE TITLE
how to change newsimage size

### ISSUE THREAD

**Issue by Jimmi08** [rica-carv/e107_theme-selospt_v2#2]
- create template folder in theme folder
- create news folder there (theme/templates/news)
- go to plugins/news/templates
- copy file news_template.php to your new theme folder
- find 
`{SETIMAGE: w=900&h=300}`
and replace it with 
`{SETIMAGE: w=900&h=900}`

I am not able to find from where is your html markup for news listing:
![image](https://cloud.githubusercontent.com/assets/5429548/13923209/ee717cc2-ef7f-11e5-8b1f-f96a8b01b92c.png)

if you have there {NEWSIMAGE: item=1} and missing SETIMAGE, just add it before it.

**Comment by rica-carv** [comment]
Seems i got it working with a news_template.php....

Closing it, but....
